const grey_tag_front = "<p style=\"color:grey\">"
const grey_tag_back = "</p>"
const logo_olap_folder_name = "logos_olap"
const logo_no_olap_folder_name = "logos_no_olap"
const pics_olap_folder_name = "pics_olap"
const pics_no_olap_folder_name = "pics_no_olap"
